/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToggleRouteImport } from './routes/toggle'
import { Route as OptimizeRouteImport } from './routes/optimize'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'

const ToggleRoute = ToggleRouteImport.update({
  id: '/toggle',
  path: '/toggle',
  getParentRoute: () => rootRouteImport,
} as any)
const OptimizeRoute = OptimizeRouteImport.update({
  id: '/optimize',
  path: '/optimize',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/optimize': typeof OptimizeRoute
  '/toggle': typeof ToggleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/optimize': typeof OptimizeRoute
  '/toggle': typeof ToggleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/optimize': typeof OptimizeRoute
  '/toggle': typeof ToggleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chat' | '/optimize' | '/toggle'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chat' | '/optimize' | '/toggle'
  id: '__root__' | '/' | '/chat' | '/optimize' | '/toggle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  OptimizeRoute: typeof OptimizeRoute
  ToggleRoute: typeof ToggleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/toggle': {
      id: '/toggle'
      path: '/toggle'
      fullPath: '/toggle'
      preLoaderRoute: typeof ToggleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optimize': {
      id: '/optimize'
      path: '/optimize'
      fullPath: '/optimize'
      preLoaderRoute: typeof OptimizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  OptimizeRoute: OptimizeRoute,
  ToggleRoute: ToggleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
